name: Practising Events
on: 
    push:
    pull_request:
        types: [opened, assigned, synchronize, reopened]
    issues:
        types: opened

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
       
                    - run: |
                        echo $GITHUB_SHA
                        echo $GITHUB_REF
                        echo "Hello world"
                    - uses: actions/checkout@v3
            

